"""order field added in courses models

Revision ID: 09df43771ccf
Revises: 66391b593acc
Create Date: 2025-08-12 17:21:00.351239

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "09df43771ccf"
down_revision: Union[str, Sequence[str], None] = "66391b593acc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contents", sa.Column("order", sa.Integer(), nullable=True))
    op.add_column("subjects", sa.Column("order", sa.Integer(), nullable=True))
    op.add_column("unit_contents", sa.Column("order", sa.Integer(), nullable=True))
    op.add_column("units", sa.Column("order", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("units", "order")
    op.drop_column("unit_contents", "order")
    op.drop_column("subjects", "order")
    op.drop_column("contents", "order")
    # ### end Alembic commands ###
