"""add instructor and image in course model

Revision ID: 32be7ac3f429
Revises: 5e6a4f2d2a59
Create Date: 2025-08-13 10:26:18.490392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "32be7ac3f429"
down_revision: Union[str, Sequence[str], None] = "5e6a4f2d2a59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("instructor_id", sa.Integer(), nullable=True))
    op.add_column(
        "courses",
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_foreign_key(None, "courses", "users", ["instructor_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "courses", type_="foreignkey")
    op.drop_column("courses", "image_url")
    op.drop_column("courses", "instructor_id")
    # ### end Alembic commands ###
