"""gamification module

Revision ID: 3e5806b118aa
Revises: 32be7ac3f429
Create Date: 2025-08-13 14:43:04.473385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3e5806b118aa"
down_revision: Union[str, Sequence[str], None] = "32be7ac3f429"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_expirable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        "streak_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_streak_types_id"), "streak_types", ["id"], unique=False)
    op.create_table(
        "user_achievements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("achieved_by_id", sa.Integer(), nullable=False),
        sa.Column("achievement_type_id", sa.Integer(), nullable=False),
        sa.Column("achieved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["achieved_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["achievement_type_id"],
            ["achievements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_achievements_achieved_by_id"),
        "user_achievements",
        ["achieved_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_achievements_achievement_type_id"),
        "user_achievements",
        ["achievement_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_achievements_id"), "user_achievements", ["id"], unique=False
    )
    op.create_table(
        "user_streaks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("streak_by_id", sa.Integer(), nullable=False),
        sa.Column("streak_type_id", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("longest_streak", sa.Integer(), nullable=False),
        sa.Column("last_action", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["streak_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["streak_type_id"],
            ["streak_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_streaks_id"), "user_streaks", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_streaks_streak_by_id"),
        "user_streaks",
        ["streak_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_streaks_streak_type_id"),
        "user_streaks",
        ["streak_type_id"],
        unique=False,
    )
    op.create_index(op.f("ix_achievements_id"), "achievements", ["id"], unique=False)
    op.create_index(op.f("ix_contents_id"), "contents", ["id"], unique=False)
    op.create_index(
        op.f("ix_contents_unit_content_id"),
        "contents",
        ["unit_content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_ratings_course_id"),
        "course_ratings",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_ratings_id"), "course_ratings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_course_ratings_user_id"), "course_ratings", ["user_id"], unique=False
    )
    op.add_column(
        "courses",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(op.f("ix_courses_id"), "courses", ["id"], unique=False)
    op.create_index(
        op.f("ix_courses_instructor_id"), "courses", ["instructor_id"], unique=False
    )
    op.create_index(op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True)
    op.create_index(
        op.f("ix_subjects_course_id"), "subjects", ["course_id"], unique=False
    )
    op.create_index(op.f("ix_subjects_id"), "subjects", ["id"], unique=False)
    op.create_index(op.f("ix_unit_contents_id"), "unit_contents", ["id"], unique=False)
    op.create_index(
        op.f("ix_unit_contents_unit_id"), "unit_contents", ["unit_id"], unique=False
    )
    op.create_index(op.f("ix_units_id"), "units", ["id"], unique=False)
    op.create_index(op.f("ix_units_subject_id"), "units", ["subject_id"], unique=False)
    op.create_index(
        op.f("ix_user_contents_content_id"),
        "user_contents",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_contents_status"), "user_contents", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_user_contents_user_id"), "user_contents", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_courses_course_id"), "user_courses", ["course_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_courses_status"), "user_courses", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_user_courses_user_id"), "user_courses", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_units_status"), "user_units", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_user_units_unit_id"), "user_units", ["unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_units_user_id"), "user_units", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_index(
        op.f("ix_usersubject_status"), "usersubject", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_usersubject_subject_id"), "usersubject", ["subject_id"], unique=False
    )
    op.create_index(
        op.f("ix_usersubject_user_id"), "usersubject", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usersubject_user_id"), table_name="usersubject")
    op.drop_index(op.f("ix_usersubject_subject_id"), table_name="usersubject")
    op.drop_index(op.f("ix_usersubject_status"), table_name="usersubject")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.create_unique_constraint(
        op.f("users_username_key"),
        "users",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_user_units_user_id"), table_name="user_units")
    op.drop_index(op.f("ix_user_units_unit_id"), table_name="user_units")
    op.drop_index(op.f("ix_user_units_status"), table_name="user_units")
    op.drop_index(op.f("ix_user_courses_user_id"), table_name="user_courses")
    op.drop_index(op.f("ix_user_courses_status"), table_name="user_courses")
    op.drop_index(op.f("ix_user_courses_course_id"), table_name="user_courses")
    op.drop_index(op.f("ix_user_contents_user_id"), table_name="user_contents")
    op.drop_index(op.f("ix_user_contents_status"), table_name="user_contents")
    op.drop_index(op.f("ix_user_contents_content_id"), table_name="user_contents")
    op.drop_index(op.f("ix_units_subject_id"), table_name="units")
    op.drop_index(op.f("ix_units_id"), table_name="units")
    op.drop_index(op.f("ix_unit_contents_unit_id"), table_name="unit_contents")
    op.drop_index(op.f("ix_unit_contents_id"), table_name="unit_contents")
    op.drop_index(op.f("ix_subjects_id"), table_name="subjects")
    op.drop_index(op.f("ix_subjects_course_id"), table_name="subjects")
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.create_unique_constraint(
        op.f("profiles_user_id_key"),
        "profiles",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("profiles", "avatar")
    op.drop_index(op.f("ix_courses_instructor_id"), table_name="courses")
    op.drop_index(op.f("ix_courses_id"), table_name="courses")
    op.drop_column("courses", "description")
    op.drop_index(op.f("ix_course_ratings_user_id"), table_name="course_ratings")
    op.drop_index(op.f("ix_course_ratings_id"), table_name="course_ratings")
    op.drop_index(op.f("ix_course_ratings_course_id"), table_name="course_ratings")
    op.drop_index(op.f("ix_contents_unit_content_id"), table_name="contents")
    op.drop_index(op.f("ix_contents_id"), table_name="contents")
    op.add_column(
        "achievements",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "achievements",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_achievements_id"), table_name="achievements")
    op.drop_column("achievements", "is_active")
    op.drop_column("achievements", "is_expirable")
    op.drop_column("achievements", "icon")
    op.drop_index(op.f("ix_user_streaks_streak_type_id"), table_name="user_streaks")
    op.drop_index(op.f("ix_user_streaks_streak_by_id"), table_name="user_streaks")
    op.drop_index(op.f("ix_user_streaks_id"), table_name="user_streaks")
    op.drop_table("user_streaks")
    op.drop_index(op.f("ix_user_achievements_id"), table_name="user_achievements")
    op.drop_index(
        op.f("ix_user_achievements_achievement_type_id"), table_name="user_achievements"
    )
    op.drop_index(
        op.f("ix_user_achievements_achieved_by_id"), table_name="user_achievements"
    )
    op.drop_table("user_achievements")
    op.drop_index(op.f("ix_streak_types_id"), table_name="streak_types")
    op.drop_table("streak_types")
    # ### end Alembic commands ###
