"""foreign key reference changed

Revision ID: 593907ad13fe
Revises: bd513c06150a
Create Date: 2025-08-06 10:27:17.114214

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "593907ad13fe"
down_revision: Union[str, Sequence[str], None] = "bd513c06150a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("contents_unit_content_id_fkey"), "contents", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_contents_unit_content_id"),
        "contents",
        "unit_contents",
        ["unit_content_id"],
        ["id"],
    )
    op.drop_constraint(op.f("units_subject_id_fkey"), "units", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_units_subject_id"), "units", "subjects", ["subject_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_units_subject_id"), "units", type_="foreignkey")
    op.create_foreign_key(
        op.f("units_subject_id_fkey"), "units", "courses", ["subject_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_contents_unit_content_id"), "contents", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("contents_unit_content_id_fkey"),
        "contents",
        "units",
        ["unit_content_id"],
        ["id"],
    )
    # ### end Alembic commands ###
