"""added rating and price in course

Revision ID: 5e6a4f2d2a59
Revises: 09df43771ccf
Create Date: 2025-08-12 22:57:58.650214

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5e6a4f2d2a59"
down_revision: Union[str, Sequence[str], None] = "09df43771ccf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_ratings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("remarks", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("courses", sa.Column("price", sa.Float(), nullable=True))
    op.add_column("courses", sa.Column("completion_time", sa.Integer(), nullable=True))
    op.add_column("units", sa.Column("completion_time", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("units", "completion_time")
    op.drop_column("courses", "completion_time")
    op.drop_column("courses", "price")
    op.drop_table("course_ratings")
    # ### end Alembic commands ###
