"""rename fields

Revision ID: 66391b593acc
Revises: 593907ad13fe
Create Date: 2025-08-07 10:11:52.458538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '66391b593acc'
down_revision: Union[str, Sequence[str], None] = '593907ad13fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_contents', sa.Column('expected_completion_time', sa.Integer(), nullable=False))
    op.drop_column('user_contents', 'expected_content_completion_time')
    op.add_column('user_courses', sa.Column('expected_completion_time', sa.Integer(), nullable=False))
    op.drop_column('user_courses', 'expected_course_completion_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_courses', sa.Column('expected_course_completion_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_courses', 'expected_completion_time')
    op.add_column('user_contents', sa.Column('expected_content_completion_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_contents', 'expected_completion_time')
    # ### end Alembic commands ###
