"""add model for enrollment

Revision ID: 81375e3c0ad0
Revises: c37387ca6583
Create Date: 2025-08-25 10:28:32.273515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81375e3c0ad0'
down_revision: Union[str, Sequence[str], None] = 'c37387ca6583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_enrollments',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.Enum('PAYPAL', 'STRIPE', 'GPAY', 'MOBILE_BANKING', name='paymentmethod'), nullable=False),
    sa.Column('provider_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'REJECTED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('failure_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failure_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_enrollments_course_id'), 'course_enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_currency'), 'course_enrollments', ['currency'], unique=False)
    op.create_index(op.f('ix_course_enrollments_provider'), 'course_enrollments', ['provider'], unique=False)
    op.create_index(op.f('ix_course_enrollments_provider_payment_id'), 'course_enrollments', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_status'), 'course_enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_course_enrollments_user_id'), 'course_enrollments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_enrollments_user_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_status'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_provider_payment_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_provider'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_currency'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_course_id'), table_name='course_enrollments')
    op.drop_table('course_enrollments')
    # ### end Alembic commands ###
