"""achievements and streak_type linked

Revision ID: 8e3dbb69c76e
Revises: 880658aaab99
Create Date: 2025-09-22 12:31:36.141636

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8e3dbb69c76e"
down_revision: Union[str, Sequence[str], None] = "880658aaab99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "achievements", sa.Column("streak_type_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "achievements", "streak_types", ["streak_type_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "achievements", type_="foreignkey")
    op.drop_column("achievements", "streak_type_id")
    # ### end Alembic commands ###
