"""achievement rules set

Revision ID: a538a639bb0d
Revises: 189104091a0c
Create Date: 2025-09-23 15:23:55.489739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a538a639bb0d"
down_revision: Union[str, Sequence[str], None] = "189104091a0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

achievement_rule_set = sa.Enum(
    "COURSE", "SUBJECT", "UNIT", "STREAK", "ENROLLMENT", name="achievementruleset"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    achievement_rule_set.create(op.get_bind())
    op.add_column(
        "achievements", sa.Column("rule_type", achievement_rule_set, nullable=True)
    )
    op.add_column("achievements", sa.Column("threshold", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("achievements", "threshold")
    op.drop_column("achievements", "rule_type")
    achievement_rule_set.drop(op.get_bind())
    # ### end Alembic commands ###
