"""update content model

Revision ID: a6e8b48488b1
Revises: 3e5806b118aa
Create Date: 2025-08-14 17:28:34.538734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a6e8b48488b1'
down_revision: Union[str, Sequence[str], None] = '3e5806b118aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('content_type', sa.Enum('VIDEO', 'TEXT', 'IMAGE', 'CODE', name='contenttypeenum'), nullable=False))
    op.add_column('contents', sa.Column('completion_time', sa.Integer(), nullable=False))
    op.alter_column('contents', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contents', 'unit_content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_contents_unit_content_id'), table_name='contents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contents_unit_content_id'), 'contents', ['unit_content_id'], unique=False)
    op.alter_column('contents', 'unit_content_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contents', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('contents', 'completion_time')
    op.drop_column('contents', 'content_type')
    # ### end Alembic commands ###
