"""add status, description and objective in course models

Revision ID: c37387ca6583
Revises: e08cff4e7e89
Create Date: 2025-08-20 14:15:11.895270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c37387ca6583'
down_revision: Union[str, Sequence[str], None] = 'e08cff4e7e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('status', sa.Enum('PUBLISHED', 'ARCHIVED', 'DRAFT', name='statusenum'), nullable=True))
    op.add_column('subjects', sa.Column('status', sa.Enum('PUBLISHED', 'ARCHIVED', 'DRAFT', name='statusenum'), nullable=True))
    op.add_column('subjects', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subjects', sa.Column('objectives', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('units', sa.Column('status', sa.Enum('PUBLISHED', 'ARCHIVED', 'DRAFT', name='statusenum'), nullable=True))
    op.add_column('units', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('units', sa.Column('objectives', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'objectives')
    op.drop_column('units', 'description')
    op.drop_column('units', 'status')
    op.drop_column('subjects', 'objectives')
    op.drop_column('subjects', 'description')
    op.drop_column('subjects', 'status')
    op.drop_column('courses', 'status')
    # ### end Alembic commands ###
