"""unit content remove and new timestamp model

Revision ID: f546f55c0c48
Revises: 81375e3c0ad0
Create Date: 2025-08-26 15:46:18.459691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f546f55c0c48"
down_revision: Union[str, Sequence[str], None] = "81375e3c0ad0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_time_stamps",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.Column("time_stamp", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_video_time_stamps_id"), "video_time_stamps", ["id"], unique=False
    )
    op.add_column("contents", sa.Column("unit_id", sa.Integer(), nullable=True))
    op.add_column(
        "contents",
        sa.Column(
            "status",
            sa.Enum("PUBLISHED", "ARCHIVED", "DRAFT", name="statusenum"),
            nullable=True,
        ),
    )
    op.drop_constraint(
        op.f("fk_contents_unit_content_id"), "contents", type_="foreignkey"
    )
    op.create_foreign_key(None, "contents", "units", ["unit_id"], ["id"])
    op.drop_column("contents", "unit_content_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contents",
        sa.Column("unit_content_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "contents", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_contents_unit_content_id"),
        "contents",
        "unit_contents",
        ["unit_content_id"],
        ["id"],
    )
    op.drop_column("contents", "status")
    op.drop_column("contents", "unit_id")
    op.drop_index(op.f("ix_video_time_stamps_id"), table_name="video_time_stamps")
    op.drop_table("video_time_stamps")
    # ### end Alembic commands ###
